
version: "3.4"
services:
    namenode:
        image: davann/namenode:2.0
        # container_name: namenode
        environment:
            - NAMENODE_HOST=namenode
            - DATANODE_HOST=datanode
            - HOST_IP=192.168.19.128
        hostname: namenode
        # environment:
        #     - HOST_IP=192.168.3.106
        networks:
            - hadoop-network
        ports:
            - "9870:9870"   # Namenode web UI
            - "9000:9000"   # HDFS client (fs.defaultFS)
        volumes:
            - namenode-data:/data/hadoop/hdfs/namenode
        deploy:
            replicas: 1
            placement:
                constraints:
                - node.role == manager
    datanode:
        image: davann/datanode:2.0
        # container_name: datanode
        environment:
            - NAMENODE_HOST=namenode
            - DATANODE_HOST=datanode
            - HOST_IP=192.168.19.128
        hostname: datanode
        networks:
            - hadoop-network
        ports:
            - "9864:9864"   # Datanode web UI
        volumes:
            - datanode-data:/data/hadoop/hdfs/datanode
        depends_on:
            - namenode
        deploy:
            replicas: 2
            placement:
                constraints:
                    - node.role == worker
volumes:
    namenode-data:
        driver: local
        name: namenode-data
    datanode-data:
        driver: local
        name: datanode-data

networks:
    hadoop-network:
        driver: overlay
