version: "3.4"
services:
    namenode:
        image: hbase_namenode:latest
        environment:
            - NAMENODE_HOST=namenode
            - DATANODE_HOST=datanode
            - HOST_IP=192.168.1.185
        hostname: namenode
        networks:
            - hadoop-network
        ports:
            - "9870:9870"   # Namenode web UI
            - "9000:9000"   # HDFS client (fs.defaultFS)
        volumes:
            - namenode-data:/data/hadoop/hdfs/namenode

    datanode:
        image: hbase_datanode:latest
        environment:
            - NAMENODE_HOST=namenode
            - DATANODE_HOST=datanode
            - HOST_IP=192.168.6.218
        hostname: datanode
        networks:
            - hadoop-network
        ports:
            - "9864:9864"   # Datanode web UI
        volumes:
            - datanode-data:/data/hadoop/hdfs/datanode
        depends_on:
            - namenode

    hmaster:
        image: hbase:latest
        hostname: hmaster
        environment:
            - ROLE=master
            - HOSTNAME=hmaster
            - HMASTER_HOST=hmaster
            - NAMENODE_HOST=namenode
            - ZOOKEEPER_HOST=zookeeper
        networks:
            - hadoop-network
        depends_on:
            - datanode
            - namenode
            - zookeeper
        ports:
          - "16000:16000"   # HBase Master
          - "16010:16010"   # HBase Master Web UI
    hregionserver:
        image: hbase:latest
        hostname: hregionserver
        environment:
            - ROLE=regionserver
            - HOSTNAME=hregionserver
            - HMASTER_HOST=hmaster
            - NAMENODE_HOST=namenode
            - ZOOKEEPER_HOST=zookeeper
        networks:
            - hadoop-network
        depends_on:
            - datanode
            - namenode
            - zookeeper
            - hmaster
        ports:
          - "16020:16020"   # HBase RegionServer
          - "16030:16030"   # HBase RegionServer Web UI
    zookeeper:
        image: zookeeper:latest
        hostname: zookeeper
        networks:
            - hadoop-network
        volumes:
            - hbase_zookeeper:/opt/zookeeper/data
        ports:
          - "2181:2181"   # Zookeeper Client
          - "2888:2888"   # Zookeeper Quorum
          - "3888:3888"   # Zookeeper Leader Election
        depends_on:
            - datanode
volumes:
    namenode-data:
        driver: local
        name: namenode-data
    datanode-data:
        driver: local
        name: datanode-data
    hbase_zookeeper:
        name: hbase_zookeeper
        driver: local
networks:
    hadoop-network:
        driver: bridge
        
